// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        pgtype.UUID
	HeightCm  pgtype.Numeric
	HeightIn  pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
