// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, height_cm)
VALUES ($1, $2)
RETURNING id, height_cm, height_in, created_at
`

type CreateCustomerParams struct {
	ID       pgtype.UUID
	HeightCm pgtype.Numeric
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.ID, arg.HeightCm)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.HeightCm,
		&i.HeightIn,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, height_cm, height_in, created_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.HeightCm,
		&i.HeightIn,
		&i.CreatedAt,
	)
	return i, err
}
