// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getMainSequence = `-- name: GetMainSequence :one
SELECT ID FROM Sequence
WHERE SeriesID = ?
ORDER BY Name = ? DESC, ID
LIMIT 1
`

type GetMainSequenceParams struct {
	Seriesid string
	Name     string
}

func (q *Queries) GetMainSequence(ctx context.Context, arg GetMainSequenceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMainSequence, arg.Seriesid, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}
