// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuthors = `-- name: ListAuthors :many
SELECT 
    id,
    name as name_nullable,
    bio as bio_notnull,
    count(*) over() as total_count
FROM authors
`

type ListAuthorsRow struct {
	ID           int64
	NameNullable pgtype.Text
	BioNotnull   string
	TotalCount   pgtype.Int8
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameNullable,
			&i.BioNotnull,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
