// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getOne = `-- name: GetOne :one
SELECT id, xYz, barBaz FROM foo WHERE id = ?
`

func (q *Queries) GetOne(ctx context.Context, id int64) (Foo, error) {
	row := q.db.QueryRowContext(ctx, getOne, id)
	var i Foo
	err := row.Scan(&i.ID, &i.Xyz, &i.Barbaz)
	return i, err
}
