// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

const upsertExperienceLocations = `-- name: UpsertExperienceLocations :copyfrom
INSERT INTO experience_locations (location_id, type)
VALUES (?, ?)
`

type UpsertExperienceLocationsParams struct {
	LocationID string
	Type       ExperienceLocationsType
}
